account/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views


app_name = "account"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("registration/", views.RegistrationView.as_view(), name="registration"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("update/<int:pk>/", views.AccountUpdateView.as_view(), name="update_user"),
    path("update/pass<int:pk>/", views.PassUpdateView.as_view(), name="update_pass"),
    path("update/photo<int:pk>/", views.PhotoUpdateView.as_view(), name="update_photo"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mainapp.urls")),
    path("account/", include("account.urls")),
    # ckeditor
    path("ckeditor/", include("ckeditor_uploader.urls")),
    # капча
    path("captcha/", include("captcha.urls")),
]

if settings.DEBUG:
    # Django debug toolbar
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

# кэширование
from django.views.decorators.cache import cache_page

from . import views


time_cache = 60    # время хранения кеша 60 секунд
app_name = "mainapp"

urlpatterns = [
    # companies page (main)
    path("", views.MainListView.as_view(), name="main_page"),
    path("company/<int:pk>/", cache_page(time_cache)(views.DetailCompanyView.as_view()), name="detail_company"),
    path("company/create_new/", views.CreateCompanyView.as_view(), name="create_company"),
    path("company/<int:pk>/update/", views.CompanyUpdateView.as_view(), name="update_company"),
    path("company/<int:pk>/delete/", views.CompanyDeleteView.as_view(), name="delete_company"),
    # projects page
    path("projects/", cache_page(time_cache)(views.ProjectsListView.as_view()), name="projects_page"),
    path("project/<int:pk>/", cache_page(time_cache)(views.DetailProjectView.as_view()), name="detail_project"),
    path("project/create_new/", views.CreateProjectView.as_view(), name="create_project"),
    path("project/<int:pk>/update/", views.ProjectUpdateView.as_view(), name="update_project"),
    path("project/<int:pk>/delete/", views.ProjectDeleteView.as_view(), name="delete_project"),
    # interaction
    path("interactions/", cache_page(time_cache)(views.InteractionListView.as_view()), name="interaction_page"),
    path("interaction/<int:pk>/", cache_page(time_cache)(views.DetailInteractionView.as_view()), name="interaction_detail"),
    path("interaction/create/", views.CreateInteractionView.as_view(), name="create_interaction"),
    path("interaction/<int:pk>/update/", views.InteractionUpdateView.as_view(), name="update_interaction"),
    path("interaction/<int:pk>/delete", views.InteractionDeleteView.as_view(), name="delete_interaction"),
    # manager
    path("user/", views.ManagerView.as_view(), name="manager"),
    # likes
    path("add_like/", views.AddLikeView.as_view(), name="like_add"),
    path("remove_like/", views.RemoveLikeView.as_view(), name="like_remove"),
]

mainapp/forms.py
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget

from .models import CompanyInformation, ProjectForCompany, Interaction


class CreateCompanyForm(forms.ModelForm):
    """
    Форма для добавления и редактирования компании (клиента)
    """
    class Meta:
        model = CompanyInformation
        fields = "__all__"

        widgets = {
            "name_company": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Компания"
            }),
            "contact_person": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Контактное лицо"
            }),
            "about_company": CKEditorUploadingWidget(),
            "address": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Адрес"
            }),
            "phone": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Номер телефона"
            }),
            "email": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Электронная почта"
            })
        }


class CreateProjectWithCompanyForm(forms.ModelForm):
    """
    Форма для добавления проекта со страницы с описанием компании
    """
    class Meta:
        model = ProjectForCompany
        fields = (
            "name_project",
            "about_project",
            "start_date",
            "finished",
            "finish_date",
            "price"
        )

        widgets = {
            "name_project": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Название проекта"
            }),
            "about_project": CKEditorUploadingWidget(),
            "start_date": forms.SelectDateWidget(attrs={}),
            "finish_date": forms.SelectDateWidget(attrs={}),
            "price": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Стоимость"
            })
        }


class CreateProjectForm(CreateProjectWithCompanyForm):
    """
    Форма для добавления проекта
    """
    CreateProjectWithCompanyForm.Meta.fields = "__all__"
    CreateProjectWithCompanyForm.Meta.widgets |= {
        "company": forms.Select(attrs={
            "class": "form-control",
            "placeholder": "Компания"
        })
    }


class CreateInteractionWithProjectForm(forms.ModelForm):
    """
    Форма для добавления и редактирования зависимости со страницы описания проекта
    """
    class Meta:
        model = Interaction
        fields = ["communication_channel", "about"]

        widgets = {
            "about": forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Описание"
            }),
            "communication_channel": forms.Select(attrs={
                "class": "form-control",
                "placeholder": "Канал общения"
            })

        }


class CreateInteractionForm(CreateInteractionWithProjectForm):
    """
    Форма для добавления зависимости
    """
    CreateInteractionWithProjectForm.Meta.fields += [
        "project",
    ]
    CreateInteractionWithProjectForm.Meta.widgets |= {
        "project": forms.Select(attrs={
            "class": "form-control",
            "placeholder": "Канал общения"
        })
    }

mainapp/views.py
from django.shortcuts import render
from django.views.generic import View, UpdateView, DeleteView, ListView, DetailView
from django.http import HttpResponseRedirect

from .filters import InteractionFilter

from .models import CompanyInformation, ProjectForCompany, Interaction, RatingInteraction
from .forms import (
    CreateCompanyForm,
    CreateProjectForm,
    CreateInteractionWithProjectForm,
    CreateProjectWithCompanyForm,
    CreateInteractionForm
)
from django.contrib.auth import get_user_model

User = get_user_model()


class MainListView(ListView):
    """
    Главная страница
    вывод всех компаний с пагинацией и сортировкой
    """
    model = CompanyInformation
    template_name = "mainapp/main_page.html"
    context_object_name = "companies"
    paginate_by = 3

    def get_ordering(self):
        ordering = self.request.GET.get("order_by")
        return ordering

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["order_by"] = self.request.GET.get("order_by")
        return context


class DetailCompanyView(View):
    """
    Вывод детальной информации о компании
    """
    def get(self, request, *args, **kwargs):
        id = kwargs.get("pk")
        company = CompanyInformation.objects.get(id=id)
        projects = ProjectForCompany.objects.filter(company__name_company=company.name_company)
        context = {
            "company": company,
            "projects": projects
        }
        return render(request, "mainapp/company_detail.html", context)


# # TODO переписать класс DetailCompanyView с View на DetailView (переделать get_absolute_url и применить его везде)
# class CompanyDetailView(DetailView):
#     """
#     Вывод детальной информации о компании с перечнем списка проектов компании
#     """
#     model = CompanyInformation
#     pk_url_kwarg = "pk"
#     template_name = "mainapp/company_detail.html"
#     context_object_name = "company"
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         return context


class CreateCompanyView(View):
    """
    Добавить новую компанию в базу
    """
    def get(self, request, *args, **kwargs):
        form = CreateCompanyForm(request.POST or None)
        context = {
            "form": form,
        }
        return render(request, "mainapp/company_create.html", context)

    def post(self, request, *args, **kwargs):
        form = CreateCompanyForm(request.POST or None)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
        else:
            context = {
                "form": form,
            }
            return render(request, "mainapp/company_create.html", context)


class CompanyUpdateView(UpdateView):
    """
    Изменение данных компании
    """
    model = CompanyInformation
    template_name = "mainapp/company_create.html"
    form_class = CreateCompanyForm


class CompanyDeleteView(DeleteView):
    """
    Удаление компании с базы
    """
    model = CompanyInformation
    template_name = "mainapp/company_delete.html"
    success_url = "/"


class ProjectsListView(ListView):
    """
    Страница вывода проектов
    """
    model = ProjectForCompany
    template_name = "mainapp/projects_in_work.html"
    context_object_name = "projects"
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        projects_status = self.request.GET.get("order_by")
        if projects_status:
            context["order_by"] = projects_status
    #         if projects_status == "in_work":
    #             projects_status = False
    #         elif projects_status == "finished":
    #             projects_status = True
    #
    #         context["projects"] = self.model.objects.filter(finished=projects_status)
    #
        return context

    def get_queryset(self):
        projects_status = self.request.GET.get("order_by")
        if projects_status:
            if projects_status == "in_work":
                projects_status = False
            elif projects_status == "finished":
                projects_status = True

            return ProjectForCompany.objects.filter(finished=projects_status)

        return ProjectForCompany.objects.all()


class DetailProjectView(View):
    """
    Вывод детальной информации о проекте
    """
    def get(self, request, *args, **kwargs):
        id = kwargs.get("pk")
        project = ProjectForCompany.objects.get(id=id)
        interactions = Interaction.objects.filter(project__name_project=project.name_project)
        context = {
            "project": project,
            "interactions": interactions
        }
        return render(request, "mainapp/project_detail.html", context)


class CreateProjectView(View):
    """
    Добавить новый проект в базу
    обработкой гет запроса
    """
    def get(self, request, *args, **kwargs):
        company_id = request.GET.get("company_id")
        if company_id:
            form = CreateProjectWithCompanyForm(request.POST or None)
        else:
            form = CreateProjectForm(request.POST or None)

        context = {
            "form": form
        }
        return render(request, "mainapp/project_create.html", context)

    def post(self, request, *args, **kwargs):
        company_id = request.GET.get("company_id")
        if company_id:
            form = CreateProjectWithCompanyForm(request.POST or None)
        else:
            form = CreateProjectForm(request.POST or None)

        if form.is_valid():
            if company_id:
                new_project = form.save(commit=False)
                new_project.company = CompanyInformation.objects.get(id=company_id)
                new_project.save()
                return HttpResponseRedirect("/projects")
            else:
                form.save()
                return HttpResponseRedirect("/projects")
        else:
            context = {
                "form": form
            }
            return render(request, "mainapp/project_create.html", context)


class ProjectUpdateView(UpdateView):
    """
    Изменение данных проекта
    """
    model = ProjectForCompany
    template_name = "mainapp/project_create.html"
    form_class = CreateProjectWithCompanyForm


class ProjectDeleteView(DeleteView):
    """
    Удаление проекта с базы
    """
    model = ProjectForCompany
    template_name = "mainapp/company_delete.html"
    success_url = "/projects"


class InteractionListView(ListView):
    """
    Вывод взаимодействий с последующей фильтрацией
    """
    model = Interaction
    context_object_name = "interactions"
    template_name = "mainapp/interaction.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = InteractionFilter(self.request.GET, queryset=self.get_queryset())

        # ! Кастомный фильтр
        # TODO доделать корректную работу фильтра и поиск по ключевым словам
        # context["companies_list"] = tuple(set([i.company.name_company for i in self.model.objects.all()]))
        # context["projects_list"] = tuple(set([i.project.name_project for i in self.model.objects.all()]))
        # company = self.request.GET.get("company")
        # project = self.request.GET.get("project")
        # if company:
        #     context["interactions"] = self.model.objects.filter(company__name_company=company)
        # elif project:
        #     context["interactions"] = self.model.objects.filter(project__name_project=project)

        return context


class DetailInteractionView(View):
    """
    Вывод отдельного сообщения
    """
    def get(self, request, *args, **kwargs):
        id = kwargs.get("pk")
        interaction = Interaction.objects.get(id=id)
        context = {
            "interaction": interaction
        }
        return render(request, "mainapp/interaction_detail.html", context)


class CreateInteractionView(View):
    """
    Добавление взаимодействия по проекту
    с обработкой гет запроса
    """
    def get(self, request, *args, **kwargs):
        project_id = request.GET.get("project_id")
        if project_id:
            project = ProjectForCompany.objects.get(id=project_id)
            form = CreateInteractionWithProjectForm(request.POST or None)
            context = {
                "form": form,
                "project": project
            }
            return render(request, "mainapp/interaction_create_with_project.html", context)
        else:
            form = CreateInteractionForm(request.POST or None)
            context = {
                "form": form,
            }
            return render(request, "mainapp/interaction_create.html", context)

    def post(self, request, *args, **kwargs):
        project_id = request.GET.get("project_id")
        if project_id:
            project = ProjectForCompany.objects.get(id=project_id)
            form = CreateInteractionWithProjectForm(request.POST or None)
            if form.is_valid():
                new_interaction = form.save(commit=False)
                new_interaction.project = ProjectForCompany.objects.get(name_project=project.name_project)
                new_interaction.company = CompanyInformation.objects.get(name_company=project.company)
                new_interaction.manager = User.objects.get(username=self.request.user.username)
                new_interaction.save()
                return HttpResponseRedirect(f"/project/{project_id}/")
            else:
                context = {
                    "form": form,
                    "project": project
                }
                return render(request, "mainapp/interaction_create_with_project.html", context)
        else:
            form = CreateInteractionForm(request.POST or None)
            if form.is_valid():

templates/mainapp/company_create.html
{% extends "mainapp/main_page.html" %}

{% block title %}Добавление / изменение компании{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated and request.user.manager_status %}
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <h3 class="h3">Добавление / изменение компании</h3>
                <br>
                <div class="features">
                    <form action="" method="post">
                        {% csrf_token %}
                        <p>{{ form.name_company }}</p>
                        <p>{{ form.contact_person }}</p>
                        <p>{{ form.address }}</p>
                        <p>{{ form.phone }}</p>
                        <p>{{ form.email }}</p>
                        <br>
                        <p>Описание
                            {{ form.media }}
                            {{ form.about_company }}
                        </p>
                        <input type="submit" class="btn btn-success" value="Применить">
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        {% include "include/no_access.html" %}
    {% endif %}
{% endblock content %}

templates/mainapp/company_detail.html
{% extends "mainapp/main_page.html" %}

{% block title %}{{ company.name_company }}{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated %}
        {% if request.user.manager_status %}
            <a href="{% url 'mainapp:update_company' company.id %}"> <button class="btn btn-primary">Редактировать данные компании</button> </a>
            <a href="{% url 'mainapp:delete_company' company.id %}"> <button class="btn btn-danger">Удалить клиента</button> </a>
        {% endif %}
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <h2 class="h2">{{ company.name_company }}</h2>
                <p><strong>Контактное лицо:</strong><br>{{ company.contact_person }}</p>
                {% autoescape off %}
                    <p><strong>Краткое описание:</strong><br>{{ company.about_company }}</p>
                {% endautoescape %}
                <p><strong>Дата создания:</strong><br>{{ company.create_date }}</p>
                <p><strong>Дата последнего изменения:</strong><br>{{ company.date_of_change }}</p>
                <p><strong>Адрес:</strong><br>{{ company.address }}</p>
                <p><strong>Номер телефона:</strong><br>{{ company.phone }}</p>
                <p><strong>E-mail:</strong><br>{{ company.email }}</p>
                <hr>
            </div>
            <h4 class="h4" style="color: green">Выполненные проекты компании</h4>
            {% if request.user.manager_status %}
                <a href="{% url 'mainapp:create_project' %}?company_id={{ company.id }}"> <button type="submit" class="btn btn-primary">Добавить проект</button> </a>
            {% endif %}
            {% for project in projects %}
                {% if project.finished %}
                    <div class="row text-center pt-3">
                        <div class="col-lg-6 m-auto">
                            {% if request.user.manager_status %}
                                <a href="{% url 'mainapp:detail_project' pk=project.id %}">
                                    <h5 class="h5">{{ project.name_project }}</h5>
                                </a>
                            {% else %}
                                <h5 class="h5">{{ project.name_project }}</h5>
                            {% endif %}
                            <p><strong><i>Стоимость:</i></strong> {{ project.price }} $</p>
                            <hr>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        {% include "include/no_access.html" %}
    {% endif %}
{% endblock content %}

templates/mainapp/interaction_detail.html
{% extends "mainapp/interaction.html" %}

{% block title %}{{ interaction.project }} - {{ interaction.manager }}{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated and request.user.manager_status %}
        <a href="{% url 'mainapp:update_interaction' pk=interaction.id %}"> <button class="btn btn-primary">Редактировать</button></a>
        <a href="{% url 'mainapp:delete_interaction' pk=interaction.id %}"> <button class="btn btn-danger">Удалить</button></a>
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                {% if request.user.username == interaction.manager %}
                    <a href="{% url 'mainapp:detail_project' pk=interaction.project.id %}"><p>Проект: {{ interaction.project }}</p></a>
                    <a href="{% url 'mainapp:detail_company' pk=interaction.company.id %}"><p>Компания: {{ interaction.company }}</p></a>
                {% else %}
                    <p>Проект: {{ interaction.project }}</p>
                    <p>Компания: {{ interaction.company }}</p>
                {% endif %}
                <p>Канал общения: {{ interaction.communication_channel }}</p>
                <p>Менеджер: {{ interaction.manager }}</p>
                <p>{{ interaction.date_create }}</p>
                <p><i>Описание: <strong>{{ interaction.about }}</strong></i></p>
                <br>
                {% include "include/like_dislike_interaction.html" with interaction_id=interaction.id %}
            </div>
        </div>
    {% else %}
        {% include "include/no_access.html" %}
    {% endif %}
{% endblock content %}

templates/mainapp/main_page.html
{% extends "base/base.html" %}

{% block title %}Наши клиенты{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated and request.user.manager_status %}
        <a href="{% url 'mainapp:create_company' %}" class="btn btn-primary">Добавить клиента</a>
    {% endif %}
    <h4 class="text-center">Клиенты</h4>
    {% if companies|length > 1 %}
        {% include "include/ordering_main_page.html" %}
    {% endif %}

    {% for company in companies %}
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                {% if request.user.is_authenticated %}
                <a href="{% url 'mainapp:detail_company' pk=company.id %}">
                    <h3 class="h3">{{ company.name_company }}</h3>
                </a>
                {% else %}
                    <h3 class="h3">{{ company.name_company }}</h3>
                {% endif %}
                <p><strong><i>Адрес:</i></strong> {{ company.address }}</p>
                <p><strong><i>E-mail:</i></strong> {{ company.email }}</p>
                <hr>
            </div>
        </div>
    {% endfor %}
    {% include "include/pagination.html" %}
{% endblock content %}

templates/mainapp/manager.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}{{ request.user.username }}{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <h2 class="text-center">
                    {% if request.user.manager_status %}
                        Кабинет менеджера
                    {% else %}
                        Пользователь
                    {% endif %}
                    <strong><span style="color: red">{{ request.user.username }}</span></strong>
                </h2>
                {% if request.user.photo %}
                    <img src="{{ request.user.photo.url }}" height="200" >
                {% else %}
                    <img src="{% static 'mainapp/img/ava.png' %}">
                {% endif %}
                <p class="text-center" style="margin-top: 15px;">Имя: {{ request.user.first_name }}</p>
                <p class="text-center" style="margin-top: 15px;">Фамилия: {{ request.user.last_name }}</p>
                <p class="text-center" style="margin-top: 15px;">Электронная почта: {{ request.user.email }}</p>
                <p>
                    <a href="{% url 'account:update_user' pk=request.user.id %}" class="btn btn-primary">Редактировать данные</a>
                    <a href="{% url 'account:update_pass' pk=request.user.id %}" class="btn btn-primary">Изменить пароль</a>
                    <a href="{% url 'account:update_photo' pk=request.user.id %}" class="btn btn-primary">Добавить фото</a>
                </p>
                <form method="get"><input type="hidden" name="check" value="{{ request.user.id }}"></form>
                {% if request.user.manager_status %}
                    <hr>
                    <div class="col">
                        <a href="{% url 'mainapp:create_company' %}" class="btn btn-success">Добавить клиента</a>
                        <a href="{% url 'mainapp:create_project' %}" class="btn btn-success">Добавить проект</a>
                        <a href="{% url 'mainapp:create_interaction' %}" class="btn btn-success">Добавить взаимодействие</a>
                    </div>
                    <hr>
                    <h4 class="h4">Мои взаимодействия:</h4>
                        {% for interaction in interactions %}
                            <p>
                                <a href="{% url 'mainapp:interaction_detail' pk=interaction.id %}">
                                    Проект: {{ interaction.project }} |
                                    Компания: {{ interaction.company }} |
                                    Канал общения: {{ interaction.communication_channel }} |
                                    Описание: {{ interaction.about }}
                                </a>
                                {% include "include/like_dislike_interaction.html" with interaction_id=interaction.id %}
                            </p>
                            <hr>
                        {% endfor %}
                {% endif %}
            </div>
        </div>
    {% else %}
        {% include "include/no_access.html" %}
    {% endif %}
{% endblock content %}

templates/mainapp/project_detail.html
{% extends "mainapp/main_page.html" %}

{% block title %}Проект {{ project.name_project }}{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated and request.user.manager_status %}
        <a href="{% url 'mainapp:update_project' project.id %}"> <button class="btn btn-primary">Редактировать данные</button> </a>
        <a href="{% url 'mainapp:delete_project' project.id %}"> <button class="btn btn-danger">Удалить проект</button> </a>
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <h2 class="h2">{{ project.name_project }}</h2>
                <p><strong>Компания:</strong><br>{{ project.company }}</p>
                {% autoescape off %}
                    <p><strong>Описание:</strong><br>{{ project.about_project }}</p>
                {% endautoescape %}
                <p><strong>Срок начала:</strong><br>{{ project.start_date }}</p>
                <p>
                    {% if project.finished %}
                        <strong><i>Статус проекта:</i></strong> Законченный
                        <p><strong>Срок окончания:</strong><br>{{ project.finish_date }}</p>
                    {% else %}
                        <strong><i>Статус проекта:</i></strong> В работе
                    {% endif %}
                </p>
                <p><strong>Стоимость:</strong><br>{{ project.price }} $</p>
                <hr>
            </div>
            <h4 class="h4" style="color: green">Взаимодействие по проекту</h4>
            <a href="{% url 'mainapp:create_interaction' %}?project_id={{ project.id }}"> <button class="btn btn-primary">Добавить взаимодействие</button> </a>
            {% for interaction in interactions %}
                <div class="row text-center pt-3">
                    <div class="col-lg-6 m-auto">
                        <p>
                            {% if request.user.username == interaction.manager.username %}
                                <a href="{% url 'mainapp:interaction_detail' pk=interaction.id %}">{{ interaction.date_create }}</a>
                            {% else %}
                                {{ interaction.date_create }}
                            {% endif %}
                            | {{ interaction.manager }} |
                            <strong>{{ interaction.about }}</strong>
                        </p>
                        <hr>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        {% include "include/no_access.html" %}
    {% endif %}
{% endblock content %}

templates/mainapp/projects.html
{% extends "base/base.html" %}

{% block title %}Проекты{% endblock title %}

{% block content %}
    <a href="{% url 'mainapp:create_project' %}"> <button class="btn btn-danger">Добавить проект</button> </a>
    {% for project in projects %}
        {% if project.finish_date %}
            <div class="row text-center pt-3">
                <div class="col-lg-6 m-auto">
                    <a href="{% url 'mainapp:detail_project' pk=project.id %}">
                        <h3 class="h3">{{ project.name_project }}</h3>
                    </a>
                    <p><strong><i>Компания:</i></strong> {{ project.company }}</p>
                    <p><strong><i>E-Стоимость:</i></strong> {{ project.price }} $</p>
                    <hr>
                </div>
            </div>
        {% endif %}
    {% endfor %}

    {% include "include/pagination.html" %}
{% endblock content %}

templates/mainapp/projects_in_work.html
{% extends "base/base.html" %}

{% block title %}Проекты{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated and request.user.manager_status %}
        <a href="{% url 'mainapp:create_project' %}" class="btn btn-primary">Добавить проект</a>
        <h4 class="text-center">Проекты</h4>
        {% include "include/filter_projects.html" %}

        {% for project in projects %}
            <div class="row text-center pt-3">
                <div class="col-lg-6 m-auto">
                    <a href="{% url 'mainapp:detail_project' pk=project.id %}">
                        <h3 class="h3">{{ project.name_project }}</h3>
                    </a>
                    <p><strong><i>Компания:</i></strong> {{ project.company }}</p>
                    <p>
                        {% if project.finished %}
                            <strong><i>Статус проекта:</i></strong> Законченный
                        {% else %}
                            <strong><i>Статус проекта:</i></strong> В работе
                        {% endif %}
                    </p>
                    <p><strong><i>Стоимость:</i></strong> {{ project.price }} $</p>
                    <hr>
                </div>
            </div>
        {% endfor %}
        {% include "include/pagination.html" %}
    {% else %}
        {% include "include/no_access.html" %}
    {% endif %}
{% endblock content %}