account/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views


app_name = "account"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("registration/", views.RegistrationView.as_view(), name="registration"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("update/<int:pk>/", views.AccountUpdateView.as_view(), name="update_user"),
    path("update/pass<int:pk>/", views.PassUpdateView.as_view(), name="update_pass"),
    path("update/photo<int:pk>/", views.PhotoUpdateView.as_view(), name="update_photo"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mainapp.urls")),
    path("account/", include("account.urls")),
    # ckeditor
    path("ckeditor/", include("ckeditor_uploader.urls")),
    # капча
    path("captcha/", include("captcha.urls")),
]

if settings.DEBUG:
    # Django debug toolbar
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

# кэширование
from django.views.decorators.cache import cache_page

from . import views


time_cache = 60    # время хранения кеша 60 секунд
app_name = "mainapp"

urlpatterns = [
    # companies page (main)
    path("", views.MainListView.as_view(), name="main_page"),
    path("company/<int:pk>/", cache_page(time_cache)(views.DetailCompanyView.as_view()), name="detail_company"),
    path("company/create_new/", views.CreateCompanyView.as_view(), name="create_company"),
    path("company/<int:pk>/update/", views.CompanyUpdateView.as_view(), name="update_company"),
    path("company/<int:pk>/delete/", views.CompanyDeleteView.as_view(), name="delete_company"),
    # projects page
    path("projects/", cache_page(time_cache)(views.ProjectsListView.as_view()), name="projects_page"),
    path("project/<int:pk>/", cache_page(time_cache)(views.DetailProjectView.as_view()), name="detail_project"),
    path("project/create_new/", views.CreateProjectView.as_view(), name="create_project"),
    path("project/<int:pk>/update/", views.ProjectUpdateView.as_view(), name="update_project"),
    path("project/<int:pk>/delete/", views.ProjectDeleteView.as_view(), name="delete_project"),
    # interaction
    path("interactions/", cache_page(time_cache)(views.InteractionListView.as_view()), name="interaction_page"),
    path("interaction/<int:pk>/", cache_page(time_cache)(views.DetailInteractionView.as_view()), name="interaction_detail"),
    path("interaction/create/", views.CreateInteractionView.as_view(), name="create_interaction"),
    path("interaction/<int:pk>/update/", views.InteractionUpdateView.as_view(), name="update_interaction"),
    path("interaction/<int:pk>/delete", views.InteractionDeleteView.as_view(), name="delete_interaction"),
    # manager
    path("user/", views.ManagerView.as_view(), name="manager"),
    # likes
    path("add_like/", views.AddLikeView.as_view(), name="like_add"),
    path("remove_like/", views.RemoveLikeView.as_view(), name="like_remove"),
]

templates/include/django_filter_form.html
<form method="get">
    {{ filter.form }}
    <input type="submit" value="Применить">
</form>

templates/include/filter_interactions.html
 <form method="get" action="{% url 'mainapp:interaction_page' %}">
    <p>Выбрать компанию
    <select name="company" id="">
        <option value="">---</option>
        {% for company in companies_list %}
            <option value="{{ company }}">{{ company }}</option>
        {% endfor %}
    </select>
    <input type="submit" name="submit" value="Применить"/>
    </p>
</form>

<form method="get" action="">
    <p>Выбрать проект
        <select name="project" id="">
            <option value="">---</option>
            {% for project in projects_list %}
                <option value="{{ project }}">{{ project }}</option>
            {% endfor %}
        </select>
    <input type="submit" name="submit" value="Применить"/>
    </p>
</form>
<form method="get" action=""><input class="btn-danger" type="submit" name="submit" value="Сброс"/></form>

templates/include/filter_projects.html
<form method="get" action="">
    <p>Показать проекты:
    <select name="order_by">
        <option value="">Все</option>
        <option value="in_work">Не законченные</option>
        <option value="finished">Законченные</option>
    </select>
    <input type="submit" name="submit" value="Применить"/>
    </p>
</form>

templates/include/like_dislike_interaction.html
{% load like_dislike %}

{% is_liked interaction_id as is_liked_bool %}
{% count_likes interaction_id as likes_counter %}

{% if is_liked_bool %}
    {% interaction_likes_id interaction_id as interaction_likes_id %}
{% endif %}

<form action="{% if not is_liked_bool %}{% url 'mainapp:like_add' %}{% else %}{% url 'mainapp:like_remove' %}{% endif %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="interaction_id" value="{{ interaction_id }}">
    <input type="hidden" name="user_id" value="{{ request.user.id }}">
    <input type="hidden" name="url_from" value="{{ request.path }}">

    {% if is_liked_bool %}
        <input type="hidden" name="interaction_likes_id" value="{{ interaction_likes_id }}">
    {% endif %}

    {% if is_liked_bool %}
        <button type="submit" class="btn btn-danger">
            <span style="color: black"><i>Like</i> <strong>{{ likes_counter }}</strong></span>
        </button>
    {% else %}
        <button type="submit" class="btn btn-secondary">
            <i>Like</i> <strong>{{ likes_counter }}</strong>
        </button>
    {% endif %}

</form>

templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-light shadow">
    <div class="container d-flex justify-content-between align-items-center">
        <a class="navbar-brand text-success logo h1 align-self-center" href="{% url 'mainapp:main_page' %}">CRM</a>
        <div class="align-self-center flex-fill d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
            <div class="">
                <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
{#                  account#}
                    {% if request.user.is_authenticated and request.user.manager_status %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:main_page' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:projects_page' %}">Все проекты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:interaction_page' %}">Взаимодействия</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:manager' %}">Кабинет менеджера</a>
                    </li>
                    <li class="nav-item">
                        <span style="font-size:20px; color:orange; margin-left: 40px; margin-right: 20px;">
                            Здравствуйте менеджер,
                            <a href="{% url 'mainapp:manager' %}" style="text-decoration:none;">{{ request.user.username }}</a>
                        </span>
                        <a class="btn btn-success" href="{% url 'account:logout' %}">Выйти</a>
                    </li>
                    {% elif request.user.is_authenticated %}
                        <li class="nav-item">
                            <span style="font-size:20px; color:orange; margin-left: 40px; margin-right: 20px;">
                                Здравствуйте пользователь,
                                <a href="{% url 'mainapp:manager' %}" style="text-decoration:none;">{{ request.user.username }}</a>
                            </span>
                            <a class="btn btn-success" href="{% url 'account:logout' %}">Выйти</a>
                        </li>

                    {% else %}
                    <li class="nav-item">
                        <snap style="font-size:20px; color:#ff0000; margin-left: 20px;">Вы вошли как гость, Ваши права ограничены. пройдите авторизацию.</snap>
                    </li>
                    <li class="nav-item" style="margin-left: 20px; margin-right: 10px;">
                        <a class="btn btn-success" href="{% url 'account:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary" href="{% url 'account:registration' %}">Регистрация</a>
                    </li>
                    {% endif %}
{#                account#}
                </ul>
            </div>
        </div>
    </div>
</nav>

templates/include/no_access.html
<h3 class="text-center" style="color: red">У вас нет доступа к этой странице</h3>

templates/include/ordering_main_page.html
<form method="get" action="">
    <p>Сортировка
    <select name="order_by" id="">
        <option value="">---</option>
        <option value="name_company">По названию (прямая)</option>
        <option value="-name_company">По названию (обратная)</option>
        <option value="create_date">По дате создания (убывание)</option>
        <option value="-create_date">По дате создания (обратная)</option>
    </select>
    <input type="submit" name="" value="Применить"/>
    </p>
</form>

templates/include/pagination.html
<div class="col-lg-1 m-auto pt-4">
    {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if order_by %}&order_by={{ order_by }}{% endif %}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for page in page_obj.paginator.page_range %}
                    {% if page_obj.number == page %}
                        <li class="page-item active"><snap class="page-link">{{ page }}</snap></li>
                    {% elif page > page_obj.number|add:-3 and page < page_obj.number|add:3 %}
                        <li class="page-item"><a class="page-link" href="?page={{ page }}{% if order_by %}&order_by={{ order_by }}{% endif %}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if order_by %}&order_by={{ order_by }}{% endif %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}

            </ul>
        </nav>
    {% endif %}
</div>

templates/include/search.html
<form method="get">
    <label>
        <input type="text" name="search">
    </label>
    <input type="submit" value="Искать">
</form>